"""user email

Revision ID: 04b1e459cee6
Revises: c80898f98833
Create Date: 2026-10-05 21:45:08.839814

The column is nullable, so every existing row simply gets NULL — there is no
data step. `downgrade` drops the column and with it every address recorded
since; export `user.email` first on any database worth keeping.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04b1e459cee6"
down_revision: str | Sequence[str] | None = "c80898f98833"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(length=254), nullable=True))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
