"""user role and active flag

Revision ID: 2d828bd93caf
Revises: f473a272a28b
Create Date: 2026-09-30 10:48:14.306136

Both columns carry a `server_default`, so this migration needs no separate
data step: `upgrade` backfills every existing row to `role='user'`,
`is_active=true` in the same statement that adds the column.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d828bd93caf"
down_revision: str | Sequence[str] | None = "f473a272a28b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sa.String(length=20), server_default="user", nullable=False)
    )
    op.add_column(
        "user",
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    op.drop_column("user", "role")
    # ### end Alembic commands ###
