"""comment and task assignment

Revision ID: c80898f98833
Revises: 2d828bd93caf
Create Date: 2026-10-01 16:38:44.516563

Both tables are new and start empty, so there is no data step. `downgrade`
drops them and with them any recorded comments and assignment history; dump
`comment` and `task_assignment` first on any database worth keeping.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c80898f98833"
down_revision: str | Sequence[str] | None = "2d828bd93caf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["user.id"], name=op.f("fk_comment_author_id_user"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_comment_task_id_task"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
    )
    op.create_index(op.f("ix_comment_author_id"), "comment", ["author_id"], unique=False)
    op.create_index(op.f("ix_comment_task_id"), "comment", ["task_id"], unique=False)
    op.create_table(
        "task_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("assigned_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["user.id"],
            name=op.f("fk_task_assignment_assigned_by_id_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
            name=op.f("fk_task_assignment_assignee_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name=op.f("fk_task_assignment_task_id_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_assignment")),
    )
    op.create_index(
        op.f("ix_task_assignment_assigned_by_id"),
        "task_assignment",
        ["assigned_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_assignment_assignee_id"), "task_assignment", ["assignee_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_assignment_task_id"), "task_assignment", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_assignment_task_id"), table_name="task_assignment")
    op.drop_index(op.f("ix_task_assignment_assignee_id"), table_name="task_assignment")
    op.drop_index(op.f("ix_task_assignment_assigned_by_id"), table_name="task_assignment")
    op.drop_table("task_assignment")
    op.drop_index(op.f("ix_comment_task_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_author_id"), table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
