"""task priority and bookmarks

Revision ID: f473a272a28b
Revises: fc836f897d10
Create Date: 2026-09-30 07:40:36.899344

`task.priority` carries a `server_default`, so this migration needs no
separate data step: `upgrade` backfills every existing task to `medium`
priority in the same statement that adds the column. `task_bookmark` is a
brand-new table, so it starts empty regardless.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f473a272a28b"
down_revision: str | Sequence[str] | None = "fc836f897d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_bookmark",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_task_bookmark_task_id_task"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_task_bookmark_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "task_id", name=op.f("pk_task_bookmark")),
    )
    op.create_index("ix_task_bookmark_task_id", "task_bookmark", ["task_id"], unique=False)
    op.add_column(
        "task", sa.Column("priority", sa.String(length=20), server_default="medium", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "priority")
    op.drop_index("ix_task_bookmark_task_id", table_name="task_bookmark")
    op.drop_table("task_bookmark")
    # ### end Alembic commands ###
