"""user hashed password

Revision ID: fc836f897d10
Revises: f3499c05278d
Create Date: 2026-09-25 09:31:11.557458

Hand-written, not autogenerated: `add_column` with `nullable=False` and no
`server_default` touches no data — a deliberate choice (decision 4 in
plans/260925-0817-jwt-oauth2-auth/decisions.md), not an oversight. On a
database that already holds users, `upgrade` fails with Postgres's own
"column contains null values" error, because there is no hash to backfill one
with. Fix it by clearing the table first:

    DELETE FROM "user";

`task.assignee_id` and `project.owner_id` are both `ON DELETE SET NULL`, so
existing tasks and projects survive that delete untouched — only the user
rows themselves, and the credential-less accounts they represent, are gone.
There is no other remedy: no password to hash for a row this migration has
never seen.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc836f897d10"
down_revision: str | Sequence[str] | None = "f3499c05278d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("user", sa.Column("hashed_password", sa.String(length=60), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("user", "hashed_password")
